apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tags-deployment
  name: tags-deployment
  namespace: tags
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tags-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tags-deployment
    spec:
      containers:
      - image: 109412806537.dkr.ecr.us-east-1.amazonaws.com/hik-test:latest
        name: tags-deployment


